googleapis/python-spanner-django

.kokoro/build.sh, .kokoro/continuous/common.cfg, .kokoro/continuous/continuous.cfg, .kokoro/presubmit/common.cfg, .kokoro/presubmit/presubmit.cfg, .kokoro/release.sh, .kokoro/release/common.cfg, .kokoro/release/release.cfg, .kokoro/trampoline.sh
=> add .kokoro for CI on Google Cloud

.kokoro/build.sh, .kokoro/continuous/admin_to_annotations.cfg, .kokoro/continuous/backends_to_cache.cfg, .kokoro/presubmit/admin_to_annotations.cfg, .kokoro/presubmit/backends_to_cache.cfg, django_test_suite.sh
=> .kokoro: add flake8, isort + Django apps

.kokoro/build.sh, django_test_suite.sh, parallelize_tests.go
Adding apps one by one to get an idea for how long
tests will run for.
Updates #289
=> .kokoro: piecemeal add more apps to DJANGO_TEST_APPS

django_spanner/features.py
Seems to have been fixed since the failure was reported.
fixes #135
=> ci: remove admin_changelist.tests.ChangeListTests.test_multiuser_edit from skips

README.md, django_spanner/__init__.py, django_spanner/utils.py, setup.py
(from https://github.com/cockroachdb/django-cockroachdb/pull/112)
=> add Django version compatibility check

django_spanner/schema.py
Changing nullability of fields with indexes from Meta.indexes isn't
supported.
refs #378
=> django: allow changing nullability of fields with db_index=True

django_spanner/features.py, django_test_apps.txt
=> ci: add migrations tests

django_spanner/base.py, django_spanner/validation.py
=> django: add system check error for DecimalField

django_spanner/base.py, django_spanner/features.py, django_spanner/lookups.py
=> django: fix (i)contains, (i)startswith, and (i)endswith lookups with F expression crash

django_spanner/features.py, django_spanner/lookups.py
=> django: fix (i)contains, (i)startswith, and (i)endswith lookups with database function crash

django_spanner/lookups.py
Regression in ff3f43d897c54e3a678811d4f076956975ec721a.
fixes #427
=> django: make iendswith case-insensitive

django_spanner/lookups.py
=> django: fix regex lookup with F expression crash

django_spanner/lookups.py, django_test_apps.txt
=> django: fix lookup crash with multiple target fields

django_spanner/features.py
=> ci: add back migration_test_data_persistence skip

django_spanner/features.py, django_spanner/lookups.py
=> django: fix pattern lookups with bilateral transform

README.md, examples/from-scratch/README.md, examples/healthchecks/README.md
=> README, examples: add django_spanner as first entry into INSTALLED_APPS

.kokoro/build.sh
This reverts commit 7959874a6f09da750533d10f90d94320e082be76.
fixes #444
=> ci: reduce number of workers for presubmit check

django_spanner/schema.py
=> django: remove SchemaEditor.quote_value() TODO

README.md
=> document that DurationField arithmetic doesn't work with dates

django_spanner/base.py, docs/conf.py, google/cloud/spanner_dbapi/version.py, setup.py, version.py
Add version file, replace some hardcoded version strings (still more to go). Also update setup.py.
Supersedes #502.
=> fix: Update version to 2.2.0a1

google/cloud/spanner_dbapi/parser.py, tests/spanner_dbapi/test_parser.py
There is a couple of issues related to the parsing functions. Trying to reduce their complexity first before starting issues.
=> refactor: update expect() parse function

README.rst
Add a "contributing" section to the README following https://github.com/googleapis/java-spanner-jdbc#contributing.
=> chore: Add "contributing" section to README

CODE_OF_CONDUCT.md
=> chore: add a Code of Conduct

tests/unit/django_spanner/test_functions.py
test: add unit test for functions
=> test: add unit test for functions

tests/unit/django_spanner/test_schema.py
test: add unit test for schema
=> test: add unit test for schema

tests/unit/django_spanner/test_introspection.py
test: add unit test for introspection
=> test: add unit test for introspection

docs/README.rst
=> Docs: fix readme import path

django_test_apps.txt, version.py
Adding tests back into django_test_apps which were removed in PR https://github.com/googleapis/python-spanner-django/pull/652
=> tests: Add tests back that were removed in PR #652

setup.py, version.py
chor: Update repo to say beta release instead of alpha
=> chor: Update repo to say beta release instead of alpha

.kokoro/samples/python3.10/common.cfg, .kokoro/samples/python3.10/continuous.cfg, .kokoro/samples/python3.10/periodic-head.cfg, .kokoro/samples/python3.10/periodic.cfg, .kokoro/samples/python3.10/presubmit.cfg
=> chor: add samples 3.10 config

README.rst
Document how to enable/disable randomly generated primary key values.
=> docs: document how to enable/disable random PK generation
