googleapis/python-spanner-django

- .kokoro/build.sh
- .kokoro/continuous/worker_1.cfg
- .kokoro/continuous/worker_2.cfg
- .kokoro/continuous/worker_3.cfg
- .kokoro/continuous/worker_4.cfg
- .kokoro/continuous/worker_5.cfg
- .kokoro/continuous/worker_6.cfg
- .kokoro/continuous/worker_7.cfg
- django_test_suite.sh
- parallelize_tests.go
Ensures that each worker creates a unique Spanner instance
which will be DELETED as the worker is exiting!
Potentially solves the issue with very low administrative
quotas for Cloud Spanner, since now each worker will have
its own limits instead of trying to use the exact same instance.
If this works, we'll be able to massively parallelize our tests!
Fixes #413.
> parallelize_tests: create a unique instance per worker

- setup.py
If setup.py imports django_spanner, Django and google.api_core.datetime_helpers
must be installed before django-spanner.
Regression in 3a244267ffc6cabe847511896a0616fa161d3bfe.
> fix django-spanner install when django and/or google-cloud aren't installed

- .kokoro/build.sh
- parallelize_tests.go
Despite us getting a quota bump, we continue to see
errors related to creating instances, for example:
https://source.cloud.google.com/results/invocations/7a40c996-e090-495d-945f-8d74f67d8473/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fworker_0/log
panic: rpc error: code = ResourceExhausted desc = Project 1065521786570 cannot add 1 nodes in region us-west2.
This change lookups the zone and then extrapolates the region
to use when creating the Cloud Spanner instance.
> parallelize_tests: use looked up region

- django_spanner/features.py
> ci: skip test_readonly_root only on Kokoro

- django_spanner/base.py
The proper name is data_type_check_constraints (no 's' after type) but
Spanner doesn't have check constraints anyway.
> django: remove unused DatabaseWrapper.data_types_check_constraints

- CONTRIBUTING.md
- README.md
(I think the README is targeted at users who don't care about this stuff.)
> docs: move test suite information to CONTRIBUTING.md

- setup.py
This is the way release-please currently expects the version to be declared. https://github.com/googleapis/release-please/blob/4e0bf11b7f4217b5c6b8cd1aa9ea4db1bce06b89/src/updaters/python/setup-py.ts#L36
For #449
> chore: declare version as separate variable

- django_spanner/__init__.py
- setup.py
> fix: update pypi package name

- .coveragerc
- noxfile.py
As suggested in #466 , this represents item 5 of the recommended list aimed to implement nox testing automation in multiple steps.
Change list:
1. Added `cover` session to `noxfile.py` + configuration parameters;
The code, at it current state, shows only 41% test coverage:
```
nox > Running session cover
nox > Creating virtual environment (virtualenv) using python.exe in .nox\cover
nox > pip install coverage pytest-cov
nox > coverage report --show-missing --fail-under=99
Name                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------
django_spanner\__init__.py                   41     41     12      0     0%   7-73
django_spanner\base.py                       49     49      2      0 …
```
> feat: Stage 5 of `nox` implementation - adding coverage targets

- README.rst
Cosmetic changes to the README for the upcoming alpha release.
Supersedes #490.
> fix: Update README for alpha release

- setup.py
Fixes this error on `twine upload`:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: BSD' is not a valid classifier.
```
> fix: Fix license classifier

- README.rst
- docs/conf.py
Use "django-google-spanner" instead of "python-spanner-django" where appropriate in README and docs.
> fix: Replace repo name with pkg name

- google/cloud/spanner_dbapi/connection.py
- google/cloud/spanner_dbapi/types.py
- tests/spanner_dbapi/test_types.py
- tests/spanner_dbapi/test_utils.py
The proposed changes represent reworked `types.py` in accordance with the **PEP-0249** [Type Objects and Constructors](https://www.python.org/dev/peps/pep-0249/#type-objects-and-constructors) specifications.
_Some of the classes implemented prior to the alpha release are not part of the DB-API standards. Those were left in for now but may be removed later in the GA release._
> feat: Implementing DB-API types according to the PEP-0249 specification

- README.rst
- django_spanner/features.py
- google/cloud/spanner_dbapi/__init__.py
- google/cloud/spanner_dbapi/connection.py
- tests/spanner_dbapi/test_connection.py
Add warnings for methods which can't be used in autocommit mode. Update `Connection()` class constructor, and cover it with unit tests.
> refactor: refactor Connection() class and cover it with unit tests

- .github/workflows/system-tests-against-emulator.yaml
- noxfile.py
Adding a workflow file to add an ability to run tests against Spanner emulator.
Django tests should be moved into nox system tests, so that we could run them on emulator.
> test: run system tests against emulator

- docs/conf.py
So backtick'd text renders as code, links as appropriate.
This is likely to cause some problems, to be merged only with the corresponding changes to the docs.
For https://github.com/googleapis/python-spanner-django/pull/549#discussion_r516241691.
> fix: Use "any" default role in sphinx

- noxfile.py
- setup.py
Fix for #554. python-spanner [dropped support for python 3.5 in v2.0.0](https://github.com/googleapis/python-spanner/releases/tag/v2.0.0), we'll do the same for the next spanner-django release.
> refactor!: Update python-spanner dep, drop py 3.5

- setup.py
Following https://github.com/googleapis/python-spanner/pull/173.
> chore: Bump google-cloud-spanner to 2.1.0

- setup.py
We're already testing against 3.8, this PR just adds the version classifier to setup.py.
> chore: Add missing py3.8 classifier

- django_spanner/base.py
It is the same patch that used in `SQLite3`, it works fine with the python-spanner-django as well.
> fix: override django autocommit to spanner

- examples/from-scratch/README.md
Remove Emmanuel's quickstart app link from from_scratch readme file and add related django doc link in readme file.
> fix: Remove old quickstart instructions link

- version.py
Like #571, bump the version number following the [2.2.1b0 release](https://github.com/googleapis/python-spanner-django/releases/tag/v2.2.1b0) to avoid using the same version number in development.
> fix: Bump version number after 2.2.1b0 release

- .kokoro/build.sh
- django_test_suite.sh
Addresses #485.
This PR replaces the version of django used in CI tests. It replaces https://github.com/timgraham/django/tree/spanner-2.2.x with https://github.com/c24t/django/tree/spanner/stable/2.2.x. We'll keep this new branch up to date with the [`stable/2.2.x` django branch](https://github.com/django/django/tree/stable/2.2.x).
The new branch has all of @timgraham's django patches, just fast-forwarded to pick up recent changes in `stable/2.2.x`. You can see the full list of those changes with `git rev-list 3ab5235d1d..34010d8ffa`.
For the full list of @timgraham's django patches, see `git rev-list 120fdc3e42..0d551deb67` or [the equivalent diff preview on GH](https://github.com/django/django/compare/stable/2.2.x...timgraham:spanner-2.2.x).
> fix: Replace, fast-forward Django CI branch

- README.rst
Various fixes and edits to the README.
> chore: README updates

- django_spanner/__init__.py
- django_spanner/features.py
- django_spanner/introspection.py
Quick mechanical change to update links in comments to use the current repo name.
`s/orijtech\/(django-spanner|spanner-orm)/googleapis\/python-spanner-django/`
> fix: Update links in comments to use googleapis repo

- noxfile.py
- tests/unit/django_spanner/test_operations.py
refactor: update coverage score in nox file and cleanup imports in test_operations
> refactor: update coverage score in nox file and cleanup imports in test_operations

- run_testing_worker.py
fix: remove delete of instance if it already exists, as it might be in use by another test
Also include WORKER_INDEX in instance name to reduce chance of clash across workers.
> fix: remove delete of instance if it already exists, as it might be in use by another test

- django_spanner/features.py
Enabling test `backends.tests.BackendTestCase.test_duplicate_table_error` as duplicate table error class now corrected to DatabaseError.
fixes #344
> test: duplicate table error class fix

- tests/system/django_spanner/test_decimal.py
Changed test_decimal_precision_limit to not check specific error msg and only check for exception class.
Since https://github.com/googleapis/python-spanner/pull/340 python spanner throws ValueError when decimal precision limit is not met. Corrected test case to expect the same exception to be raised.
fixes #645
> fix: remove error msg check from test_decimal_precision_limit

- tests/system/django_spanner/test_decimal.py
Changed test_decimal_precision_limit to not check specific error msg and only check for exception class in non emulator test case.
Since googleapis/python-spanner#340 python spanner throws ValueError when decimal precision limit is not met. Corrected test case to expect the same exception to be raised.
fixes #645
> fix: remove error msg check from test_decimal_precision_limit for non emulator test

- django_test_apps.txt
- version.py
Like #596, bump the version number following the 2.2.1b1 release to avoid using the same version number in development.
fixes #661
> fix: bump version number after 2.2.1b1 release

- README.rst
Update docs to show decimal field support and check constraints but no support for unsigned data type
> docs: update docs to show decimal field support and check constraints

- version.py
Like #652, bump the version number following the 2.2.1b2 release to avoid using the same version number in development.
> fix: Bump version number after 2.2.1b2 release

- .kokoro/samples/lint/common.cfg
- .kokoro/samples/lint/continuous.cfg
- .kokoro/samples/lint/periodic.cfg
- .kokoro/samples/lint/presubmit.cfg
- .kokoro/samples/python3.6/common.cfg
- .kokoro/samples/python3.6/continuous.cfg
- .kokoro/samples/python3.6/periodic-head.cfg
- .kokoro/samples/python3.6/periodic.cfg
- .kokoro/samples/python3.6/presubmit.cfg
- .kokoro/samples/python3.7/common.cfg
- .kokoro/samples/python3.7/continuous.cfg
- .kokoro/samples/python3.7/periodic-head.cfg
- .kokoro/samples/python3.7/periodic.cfg
- .kokoro/samples/python3.7/presubmit.cfg
- .kokoro/samples/python3.8/common.cfg
- .kokoro/samples/python3.8/continuous.cfg
- .kokoro/samples/python3.8/periodic-head.cfg
- .kokoro/samples/python3.8/periodic.cfg
- .kokoro/samples/python3.8/presubmit.cfg
- .kokoro/samples/python3.9/common.cfg
- .kokoro/samples/python3.9/continuous.cfg
- .kokoro/samples/python3.9/periodic-head.cfg
- .kokoro/samples/python3.9/periodic.cfg
- .kokoro/samples/python3.9/presubmit.cfg
- .kokoro/test-samples-against-head.sh
- .kokoro/test-samples-impl.sh
- .kokoro/test-samples.sh
- version.py
Like #688, bump the version number following the 2.2.1b3 release to avoid using the same version number in development.
Add samples kokoro test files as the same has been added in backend.
> fix: Bump version number after 2.2.1b3 release

- docs/samples.rst
Lint fix for samples in docs folder.
> docs: lint fix for samples

- README.rst
- django_spanner/features.py
- docs/changelog.md
- docs/example_from_scratch.md
- docs/example_healthchecks.md
- docs/samples.rst
Docs: fix changelog link and sample examples.
Fix: Skip test `backends.tests.BackendTestCase.test_cursor_executemany_with_empty_params_list` as Spanner does not support empty list of DML statements.
> Docs: fix changelog link and sample examples.

- .github/.OwlBot.lock.yaml
- .github/workflows/django_tests_against_emulator0.yml
- .github/workflows/django_tests_against_emulator1.yml
- .github/workflows/django_tests_against_emulator2.yml
- .github/workflows/django_tests_against_emulator3.yml
- .github/workflows/django_tests_against_emulator4.yml
- .github/workflows/django_tests_against_emulator5.yml
- .github/workflows/django_tests_against_emulator6.yml
- .github/workflows/django_tests_against_emulator7.yml
- .github/workflows/django_tests_against_emulator8.yml
- .github/workflows/django_tests_against_emulator9.yml
- .github/workflows/integration-tests-against-emulator.yml
- .kokoro/test-samples-impl.sh
- README.rst
- owlbot.py
> chore: migrate to main branch

- setup.py
downgrade google-cloud-spanner to v 3.11.1
Temporary fix for : #746
> fix: downgrade google-cloud-spanner to v 3.11.1

- examples/healthchecks/README.md
- remove the note about Django 2.2 being the only supported version (Django 3.2 seems to work too)
- change the django-google-spanner install instructions to install from PyPI
- fix Markdown formatting for python code blocks
> docs: Update Healthchecks instructions

- noxfile.py
- setup.py
- testing/constraints-3.6.txt
fixes https://github.com/googleapis/python-spanner-django/issues/746
> chore(deps): update dependency google-cloud-spanner to v3.13.0

- tests/bulk_create/tests.py
With this PR all the Django 2.2 tests should pass. Take a look at workflows in this [PR](https://github.com/googleapis/python-spanner-django/pull/772) - I've made it using this PR's branch, and all the worlflows for the version 2.2 passed fine.
> tests: skip batching tests inapproriate for Spanner

- .github/sync-repo-settings.yaml
- django_test_suite.sh
- django_test_suite_3.2.sh
- noxfile.py
chore: use django stable versions for tests hosted on python-spanner-django
> chore: use stable django versions for tests hosted on python-spanner-django

- django_spanner/__init__.py
- tests/unit/django_spanner/test_schema.py
> fix: override AutoField default value only for Spanner

- tests/sessions_tests/tests.py
Presubmits are failing for all PRs from last few months for our Django Spanner repo with this error `ModuleNotFoundError: No module named 'tests.sessions_tests'`
The changes were made in Django repo https://github.com/django/django/commit/4c2b26174f044adc4a6461154385720479eaee55 after we forked out from it to our django/stable/3.2.x branch
> fix: Fixing test_clearsessions_unsupported test

- README.rst
More details here https://github.com/googleapis/python-spanner-django/issues/883
Please see the README section before and after this PR changes -
Before this PR : https://github.com/googleapis/python-spanner-django/tree/main?tab=readme-ov-file#transaction-support-in-autocommit-mode
After this PR : https://github.com/googleapis/python-spanner-django/tree/readme_fix?tab=readme-ov-file#transaction-support-in-autocommit-mode
> fix: Fixing README.rst to fix release failure.
